### ISSUE TITLE
urgent revision

### ISSUE THREAD

**Issue by kinomichi** [noahc3/auto-h-encore#49] opened 2018-07-09 16:54 UTC
just to let you know, with the current ver. 0.4.1 there no need of manual key in the AID. that actually goes wrong. it totally overwrite of datas in the vita directory thus make completely all of my vita save games corrupt. for me, the previous ver. 0.3.2 which have the manual insert AID is better as you can specified which  vita in need to h-encored. yeay for me for losing all my save game.

thank you for your time.

**Comment by noahc3** [comment] 2018-07-09 21:34
I can't reproduce this. This program only ever touches the PCSG90096 directory within the folder of the AID supplied by QCMA. Even if the AID was wrong, it would never touch any folders with any other game data. Can you give me more information on what exactly it did, the steps you did that made it happen, and absolutely confirm you did nothing else that could have corrupted your saves?

**Comment by kinomichi** [comment] 2018-07-09 23:42
the only thing that i do out of odinary is just i dont connect it to any
vita during the process. via usb or wifi. this is because the previous
revision 0.3.x does not even needed to connect to vita. Fyi, i can just
tranfer the h-encore afterward when the process done. Is that the reason
you find?

**Comment by noahc3** [comment] 2018-07-09 23:51
You are supposed to connect the Vita now so QCMA updates the registry with the correct AID. Without that, the program doesn't know what AID to use. This is the easiest way to make everything automated without making the user do any legwork.

If you somehow made the program continue with a blank AID, what you describe would actually happen, since it would resolve ~/PS Vita/APP/[blank aid]/ or ~/PS Vita/APP// as ~/PS Vita/APP/. How did you get it to continue?

**Comment by noahc3** [comment] 2018-07-10 00:18
I've added a safety check to the detected AID length to make sure it's not blank in commit 8ada7310c0afb1ef39ae6d07c86880c642051302. That should stop this from happening by accident. I'm really sorry for your lost saves, I should have replicated this check from the old versions to begin with.

I'm still wondering how you managed to make the program continue without connecting a Vita though.

**Comment by kinomichi** [comment] 2018-07-10 01:17
That would be as easy as click the [x] / close the prompt on taskbar

**Comment by noahc3** [comment] 2018-07-10 01:25
Being able to bypass the prompt in taskbar fixed in 14a2ad118d317193343882b9f66c43bc95ab3705.

**Closed as completed by noahc3** 2018-07-10 01:25 UTC
Labels: 5. bug, 1. high priority, 4. need more info
